using System.Text;
using H;

namespace AvaloniaExtras.SourceGenerators.Extensions;

internal static class ResourceExtensions
{
    public const string TopMessage = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        """;

    public const string BottomMessage = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Roslyn doesn't clear the file when writing debug output for
        //     EmitCompilerGeneratedFiles, so I'm writing this message to
        //     make it more obvious what's going on when that happens.
        // </auto-generated>
        //------------------------------------------------------------------------------
        """;

    public static string AsGeneratedString(this Resource resource)
    {
        var sb = new StringBuilder();
        sb.AppendLine(TopMessage);
        sb.AppendLine(resource.AsString());
        sb.AppendLine(BottomMessage);
        return sb.ToString();
    }
}
